export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

// export const PLACE_ORDER = "PLACE_ORDER";only async code never action that get sdispatched to reducer
export const ORDER_START = "ORDER_START";
export const ORDER_SUCCEEDED = "ORDER_SUCCEEDED";
export const ORDER_FAILED = "ORDER_FAILED";
export const ORDER_INIT = "ORDER_INIT";


export const FETCH_ORDERS_START =  "FETCH_ORDERS_START"
export const FETCH_ORDERS_SUCCESS =  "FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAILED =  "FETCH_ORDERS_FAILED"